language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t codeitco/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codeitco/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-test2"
  env: "DockerTest2-env"
  bucket_name: "elasticbeanstalk-us-east-2-510799748847"
  bucket_path: "docker-test2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
